name: dts
description: "A Dart port of the JTS Topology Suite, a Java library for creating and manipulating vector geometry"
version: 0.1.1
homepage: https://github.com/Go-oG/dts

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  d_util: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


